apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-container
          image: nextjs-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: password
